module.exports = {
  STATUS_PENDING: '1',
  STATUS_UPLOADED: '2',
  STATUS_PROCESSED: '3',
  FILES_INDEX: 'files-index',
  FILES_INDEX_PUBLIC: 'files-index-pub',
  FILES_DATA: 'files-data',
  UPLOAD_DATA: 'upload-data',
  PREVIEW_PREFIX: 'preview:',
  FILES_PROCESS_ERROR_FIELD: 'error',
  FILES_OWNER_FIELD: 'owner',
  FILES_PUBLIC_FIELD: 'public',
  FILES_TAGS_FIELD: 'tags',
  FILES_TEMP_FIELD: 'temporary',
  WEBHOOK_RESOURCE_ID: 'gce:webhook',
  FILES_INDEX_TAGS: 'files-index-tags',
  FILES_LIST: 'files-list',
};
